function (get_sources SOURCES SOURCES_PATH)
  if (EXISTS ${SOURCES_PATH})
    file(GLOB_RECURSE SOURCES_LIST ${SOURCES_PATH}/${DEAFULT_GLOB_SOURCES})
    list(FILTER SOURCES_LIST EXCLUDE REGEX ${DEFAULT_REGEX_SOURCES_EXCLUDE})
    list(FILTER SOURCES_LIST EXCLUDE REGEX ${DEFAULT_MAIN_CPP})
    list(REMOVE_DUPLICATES SOURCES_LIST)
  else()
    message(FATAL_ERROR "Path isn't found: ${SOURCES_PATH}")
  endif()

  set(${SOURCES} ${SOURCES_LIST} PARENT_SCOPE)
endfunction()

function (add_common_target TARGET_TYPE TARGET_NAME)
  set(SOURCES_DIR ${TARGET_NAME}/${DEFAULT_SOURCE_DIR})
  set(INCLUDES_DIR ${TARGET_NAME}/${DEFAULT_INCLUDE_DIR})

  get_sources(SOURCES ${SOURCES_DIR})

  if (TARGET_TYPE STREQUAL "SHARED" OR TARGET_TYPE STREQUAL "STATIC")
    add_library(${TARGET_NAME} ${TARGET_TYPE} ${SOURCES})
  elseif (TARGET_TYPE MATCHES "EXE*")
    add_library(lib_${TARGET_NAME} STATIC ${SOURCES})
    target_include_directories(lib_${TARGET_NAME} BEFORE PRIVATE ${INCLUDES_DIR})  

    add_executable(${TARGET_NAME} ${SOURCES_DIR}/${DEFAULT_MAIN_CPP})
    target_link_libraries(${TARGET_NAME} PRIVATE lib_${TARGET_NAME})
  else()
    message(FATAL_ERROR "Unknown target type: ${TARGET_TYPE}")
  endif()

  target_include_directories(${TARGET_NAME} BEFORE PRIVATE ${INCLUDES_DIR})
endfunction()

function(add_project_application APP_NAME)
  add_common_target(EXE ${APP_NAME})
endfunction()

function(add_project_library LIB_NAME)
  if (ARGV1)
    set(LIB_TYPE ${ARGV1})
  else()
    set(LIB_TYPE STATIC)
  endif()

  add_common_target(${LIB_TYPE} ${LIB_NAME})
endfunction()

function(add_depends_libs TARGET_NAME DEPENDS_LIST)
  if (DEPENDS_LIST)
    foreach(ITEM IN ITEMS ${DEPENDS_LIST})
      get_target_property(ITEM_TYPE ${ITEM} TYPE)
      target_include_directories(${TARGET_NAME} AFTER PRIVATE ${ITEM}/${DEFAULT_INCLUDE_DIR})
      add_dependencies(${TARGET_NAME} ${ITEM})

      if (ITEM_TYPE AND ITEM_TYPE STREQUAL EXECUTABLE)
        target_link_libraries(${TARGET_NAME} PRIVATE lib_${ITEM})
      else()
        target_link_libraries(${TARGET_NAME} PRIVATE ${ITEM})
      endif()
    endforeach()
  endif()
endfunction()

function(add_project_test TEST_NAME TEST_COMMAND)
  add_test(NAME ${TEST_NAME} COMMAND $(TEST_COMMAND} "--log_level=test_suite" "--no_use_alt_stack" "--detect_memory_leaks")
  set_tests_properties(${TEST_NAME} PROPERTIES ENVIRONMENT "LLVM_PROFILE_FILE=${TEST_NAME}.profraw")
  set(PROFRAW_LIST "${PROFRAW_LIST} ${TEST_NAME}.profraw" CACHE INTERNAL "List of all profraw files")
endfunction()

function(enable_modules)
  file(GLOB_RECURSE MODULES_LIST RELATIVE ${CMAKE_SOURCE_DIR} "module.cmake")
  list(FILTER MODULES_LIST EXCLUDE REGEX "^build/|^cmake/")
  foreach(MODULE IN ITEMS ${MODULES_LIST})
    include(${MODULE})
  endforeach()
endfunction()
